### ISSUE TITLE
Can't add account on Big Sur Beta

### ISSUE THREAD

**Issue by ubuntudroid** [deszip/BitBot#18]
When clicking on "Add account" an all-empty window appears on the latest Big Sur Beta.

There is no way to enter data or paste an access token.

![CleanShot 2020-09-02 at 09 44 00](https://user-images.githubusercontent.com/519867/91951038-d8204d80-ed00-11ea-857e-296be2ea9842.png)

**Comment by deszip** [comment]
Thanks for reporting. Smth wrong with button title color on Big Sur. Will take a look.
As a workaround you can just click in the bottom left corner of the window, inside the frame :) Button is there, just invisible.

**Comment by ubuntudroid** [comment]
Workaround works perfect, many thanks! 🙏

**Comment by deszip** [comment]
You are welcome, will close after releasing version with BigSur support.

**Comment by deszip** [comment]
Latest version 1.0.1 includes fix for that.
