### ISSUE TITLE
Open build from menu

### ISSUE THREAD

**Issue by denys-meloshyn** [deszip/BitBot#22]
Is it possible to open the build from the list of builds? Seems like I can do it only in notification.

Can't also find this screen at the bottom of the image
![](https://github.com/deszip/BitBot/raw/master/screenshot-3.png)

**Comment by deszip** [comment]
Yep sure, both options, open build in browser and show logs for build (the window from the screenshot) are available in context menu on a build row:

<img width="536" alt="Снимок экрана 2020-10-03 в 17 30 48" src="https://user-images.githubusercontent.com/432462/94994115-4f662d00-059e-11eb-8725-9c82d3076b81.png">

**Comment by denys-meloshyn** [comment]
Ah, nice!
Can I give my feedback? 😄
* I would recommend maybe add humburger menu from right side of the build and show context menu also by pressing on it
* is it possible to remember size of logs window and previous location because I need to resize it every time to fit the whole line

**Comment by deszip** [comment]
Thanks for the feedback, both points added to the backlog and will appear in upcoming versions :)
