### ISSUE TITLE
Showing wrong build time, when over 60 minutes

### ISSUE THREAD

**Issue by hosy** [deszip/BitBot#33]
When the build time is over 60 minutes, it shows the wrong build time:

Sample:
- Current build time is 75 minutes
- BitBot shows 15 minutes

**Comment by deszip** [comment]
Oh, never seen 60+ min builds to test it :) I'll take a look, thanks.

**Comment by deszip** [comment]
@hosy Please check version 1.2.0 in AppStore, it has a fix for the issue you reported. Thank you :)
