### ISSUE TITLE
(Double) click on item should open build

### ISSUE THREAD

**Issue by Fabi755** [deszip/BitBot#35]
At first thanks for this tool, and it's very nice that is now available on AppStore.

It's a little bit annoying to make a right click + click on `Open Build`. It took me a few days to understand that a right click is possible.

My expectation is that a click (or double click) will open the Bitrise webpage of clicked build item (like menu `Open Build`). 

What do you think? It's a good idea to change this?

**Comment by deszip** [comment]
Thanks for kind words @Fabi755. 
Interesting how you (me in this case) don't think of some behaviours like right click menu when you built it and know it's there from the beginning. Adding double click sounds interesting (I think single one could lead to lots of occasional clicks while scrolling). I should probably ask design guys :)
