### ISSUE TITLE
Crashing on macOS Monterey 

### ISSUE THREAD

**Issue by jpike88** [deszip/BitBot#43]
Notifications work but if I click on the menu icon at the top it just goes away, seems to disappear in activity log too. No crash windows or anything though.

**Comment by deszip** [comment]
Hi @jpike88 , thanks for reporting, the only mac I have with Monterey is running beta 4 and BitBot (1.1.0) works fine. I'll try to find your crash reports in itunes connect. Maybe you have smth meaningful in logs when it crashes? Could be useful.

**Comment by jpike88** [comment]
weird... works fine now. never mind ill let you know if it persists
