### ISSUE TITLE
Crashing after Mac OS update 11.5

### ISSUE THREAD

**Issue by temirnurdin** [deszip/BitBot#44]
## What is happening?

After launching app, trying to open window leads to crash. 

[BitBotCrash.txt](https://github.com/deszip/BitBot/files/6987966/BitBot.txt)

**Comment by deszip** [comment]
Hi @temirnurdin, thanks for reporting, sorry for that, I'll definitely take a look. Can you pls tell which macOS version exactly are you on? 11.5.2?

**Comment by temirnurdin** [comment]
Hi @deszip, no worries. Yes it is latest 11.5.2. 

**Update**
I think problem was on something else. Because a few days ago when I tried to launch app showed new account page. After I entered, now works fine.

**Comment by deszip** [comment]
Thanks for the update, I'll try to investigate, I see some similar crashes in appstore. Let's keep the issue opened untill next release for reference.

**Comment by ubuntudroid** [comment]
I'm on macOS 11.6 and also experience crashes - even on clean install. 🤔

**Comment by ubuntudroid** [comment]
Actually, I'm not even sure, it's a crash - as the behavior is like described in #43

**Comment by temirnurdin** [comment]
Found partial solution. If disable analytics, seemed to work more stable.

<img width="234" alt="Screen Shot 2022-04-07 at 12 20 44 PM" src="https://user-images.githubusercontent.com/51527050/162154062-25827129-f8ec-4b88-b072-0a27c673ad15.png">

**Comment by deszip** [comment]
Yep it's Sentry core throwing sometimes, it's get stopped when you disable analytics and thats why it's working fine after that.
I was trying to use their profiling apis to tune sync operation, I'll disable it in next update, I don't need it anymore anyway.

Hope update will be ready this weekend, thanks for your patience :)

**Comment by deszip** [comment]
@ubuntudroid @temirnurdin Version 1.2.0 is available via AppStore, it has updated Sentry sdk and some fixes, feel free to give it a try. Hope crashes will go away.

**Comment by temirnurdin** [comment]
@deszip Updated, all good. Thanks.

**Comment by deszip** [comment]
Awesome
